title: soliloquy
author: Vlad Arialin
email: arialinvlad@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  soliloquy noun (plural soliloquies)
  an act of speaking one's thoughts aloud when by oneself or regardless of any hearers, especially by a character in a play

# social links
#twitter_username: your-twitter-handle
github_username:  konichuvak

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
