title: konichuvak
author: Vlad Arialin
email: arialinvlad@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  konichuvak is a portmanteau word stemming from
  japanese 'Konnichi wa' for 'hello' and russian 'chuvak' for 'dude'

# social links
#twitter_username: your-twitter-handle
github_username:  konichuvak

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima